export const ADD_ACCOUNT = 'ADD_ACCOUNT';
export const UPDATE_ACCOUNT = 'UPDATE_ACCOUNT';
export const REMOVE_ACCOUNT = 'REMOVE_ACCOUNT';

export const ADD_EXPENSE = 'ADD_EXPENSE';
export const UPDATE_EXPENSE = 'UPDATE_EXPENSE';
export const REMOVE_EXPENSE = 'REMOVE_EXPENSE';

export const ADD_INCOME = 'ADD_INCOME';
export const UPDATE_INCOME = 'UPDATE_INCOME';
export const REMOVE_INCOME = 'REMOVE_INCOME';

export const API_REQUEST_STARTED = 'API_REQUEST_STARTED';
export const API_REQUEST_ENDED = 'API_REQUEST_ENDED';

export const UPDATE_SETTINGS = 'UPDATE_SETTINGS';
