export const ADD_ACCOUNT = 'ADD_ACCOUNT';
export const UPDATE_ACCOUNT = 'UPDATE_ACCOUNT';
export const REMOVE_ACCOUNT = 'REMOVE_ACCOUNT';
export const API_REQUEST_STARTED = 'API_REQUEST_STARTED';
export const API_REQUEST_ENDED = 'API_REQUEST_ENDED';
export const UPDATE_SETTINGS = 'UPDATE_SETTINGS';
